### ISSUE TITLE
A very elementary introduction to shaves

### ISSUE THREAD

**Issue by isovector** [isovector/papers#20]
https://arxiv.org/pdf/2202.01379.pdf

**Comment by srid** [comment]
*sheaves

Just curious: are you planning to read anything on topological spaces (prerequisite for HoTT)?

**Comment by srid** [comment]
> This paper only assumes knowledge of basic linear algebra, basic group theory, and the very fundamentals of topology

Where do I read about the fundamentals of topology itself?

**Comment by isovector** [comment]
i have no plan
